# █ dcj · dotcomjack.com · MIT
# Generated by dcj-tag. Edit mark/banner.txt, not this file.

DCJ_BANNER_PLAIN=$(cat <<'DCJEOF'
██████╗  ██████╗     ██╗
██╔══██╗██╔════╝     ██║
██║  ██║██║          ██║
██║  ██║██║     ██   ██║
██████╔╝╚██████╗╚█████╔╝
╚═════╝  ╚═════╝ ╚════╝
d o t c o m j a c k
DCJEOF
)

# Bronze accent, RGB 140;106;47. Suppressed when stdout is not a TTY,
# TERM is empty or "dumb", or NO_COLOR is set (even to an empty value).
dcj_banner() {
  if [ -n "${NO_COLOR+x}" ] || [ -z "${TERM:-}" ] \
     || [ "${TERM:-}" = "dumb" ] || [ ! -t 1 ]; then
    printf '%s\n' "$DCJ_BANNER_PLAIN"
    return
  fi
  printf '%s\n' "$DCJ_BANNER_PLAIN" | while IFS= read -r row; do
    printf '\033[38;2;140;106;47m%s\033[0m\n' "$row"
  done
}
